### ISSUE TITLE
A user is able to sign in

### ISSUE THREAD

**Issue by celsom3** [Cosecha/redadalertas#17]
Account creation will be invite only. So a verification Code will be needed.

**Comment by mckennatim** [comment]
"...the ones that will report and verify raids.. will need to authenticate with Facebook and provide more personally identifiable information." Are you closed to the idea of a more general register/login authentication like apikeys and tokens? Or at least we could add some additional fake news:) outlets like twitter or google. Do you want to be able to automatically post raid info to facebook or something?
