### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by tracethompson** [Cosecha/redadalertas#50]
hi i'm interested in helping out with this - wondering if the project is still being worked on?

**Comment by alexgraffeocohen** [comment]
@tracethompson Sorry for the delay in getting back to you!

This project is still being worked on, but we are taking a new tech direction and going mobile-first using primarily React Native. We will be working on creating new issues to start putting together a beta version of the React Native app, so stay tuned if you would be interested in helping out with that!
